version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
hooks:
  ApplicationStop:
    - location: codedeploy/application_stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: codedeploy/application_start.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: codedeploy/validate_service.sh
      timeout: 300
      runas: ubuntu
