version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
hooks:
  ApplicationStop:
    - location: codedeploy/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: codedeploy/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: codedeploy/validate_server.sh
      timeout: 300
      runas: root
