version: 0.2

phases:
  install:
    commands:
      - echo install packages here.
  pre_build:
    commands:
      - echo pre build maybe install dependencies here...
  build:
    commands:
      - echo Build started on `date`
      - echo setting up codedeploy scripts...
      - echo "${DEPLOYMENT_LEVEL}"
      - |
        if [[ "$DEPLOYMENT_LEVEL" == "production"]]; then
          echo "Deploying Production";
          ls -l;
        fi;
      - echo how do we see the logs?
      - echo might use this to run mocha
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
   files:
     - '**/*'
