version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - echo installing application and dependencies...
      - node --version
      - npm --version
      - npm install
  pre_build:
    commands:
      - echo determining deployment level...
      - echo "${DEPLOYMENT_LEVEL}"
  build:
    commands:
      - echo Build started on `date`
      - npm run codedeploy:build
      - echo might use this to run mocha
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
   files:
     - 'build/*'
     - 'public/*'
     - 'src/assets/css/material-dashboard-react.css'
     - 'codedeploy/*'
     - 'appspec.yml'
